eia/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('consultor-crud/', include('eia_app.urls', namespace='consultor-crud')),
    path('users/', include("users.urls")),
    path('', include('dashboard.urls')),
    path('configuracion/', include("configuracion.urls")),
    path('medidas/', include("medidas.urls")),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, },
            name='media'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

eia_app/urls.py
'''Modulo de urls del crud del consultor '''

from django.urls import path, re_path
from .views import *  # pylint: disable=wildcard-import, unused-wildcard-import

app_name = 'eia_app'  # pylint: disable=invalid-name

urlpatterns = [ #pylint: disable=invalid-name
    path('', consultor_index, name='consultor-crud-index'),
    path('organizaciones/', OrganizacionList.as_view(),
         name='lista-organizaciones'),
    path('organizaciones/nuevo/', OrganizacionCreate.as_view(),
         name='nueva-organizacion'),
    re_path(r'^organizaciones/(?P<pk>\d+)/$', OrganizacionDetail.as_view(),
            name='detalles-organizacion'),
    re_path(r'^organizaciones/editar/(?P<pk>\d+)/$', OrganizacionUpdate.as_view(),
            name='editar-organizacion'),
    re_path(r'^organizaciones/borrar/(?P<pk>\d+)/$', OrganizacionDelete.as_view(),
            name='borrar-organizacion'),
    path('datos_proyectos/', DatosProyectoList.as_view(),
         name='lista-datos-proyectos'),
    path('datos_proyectos/nuevo/', DatosProyectoCreate.as_view(),
         name='nueva-datos-proyecto'),
    re_path(r'^datos_proyectos/(?P<pk>\d+)/$', DatosProyectoDetail.as_view(),
            name='detalles-datos-proyecto'),
    re_path(r'^datos_proyectos/editar/(?P<pk>\d+)/$', DatosProyectoUpdate.as_view(),
            name='editar-datos-proyecto'),
    re_path(r'^datos_proyectos/borrar/(?P<pk>\d+)/$', DatosProyectoDelete.as_view(),
            name='borrar-datos-proyecto'),
    re_path(r'^datos_proyectos/generar_pdf/(?P<pk>\d+)/$', ImprimirDatosDelProyecto.as_view(),
            name='imprimir-datos-proyecto'),
    path('responsables/', ResponsableList.as_view(),
         name='lista-responsables'),
    path('responsables/nuevo/', ResponsableCreate.as_view(),
         name='nuevo-responsable'),
    re_path(r'^responsables/(?P<pk>\d+)/$', ResponsableDetail.as_view(),
            name='detalles-responsable'),
    re_path(r'^responsables/editar/(?P<pk>\d+)/$', ResponsableUpdate.as_view(),
            name='editar-responsable'),
    re_path(r'^responsables/borrar/(?P<pk>\d+)/$', ResponsableDelete.as_view(),
            name='borrar-responsable'),
    path('solicitantes/', SolicitanteList.as_view(),
         name='lista-solicitantes'),
    path('solicitantes/nuevo/', SolicitanteCreate.as_view(),
         name='nuevo-solicitante'),
    re_path(r'^solicitantes/(?P<pk>\d+)/$', SolicitanteDetail.as_view(),
            name='detalles-solicitante'),
    re_path(r'^solicitantes/editar/(?P<pk>\d+)/$', SolicitanteUpdate.as_view(),
            name='editar-solicitante'),
    re_path(r'^solicitantes/borrar/(?P<pk>\d+)/$', SolicitanteDelete.as_view(),
            name='borrar-solicitante'),
    path('datos_documentos/', DatosDocumentoList.as_view(),
         name='lista-datos-documentos'),
    path('datos_documentos/nuevo/', DatosDocumentoCreate.as_view(),
         name='nuevo-datos-documento'),
    re_path(r'^datos_documentos/(?P<pk>\d+)/$', DatosDocumentoDetail.as_view(),
            name='detalles-datos-documento'),
    re_path(r'^datos_documentos/editar/(?P<pk>\d+)/$', DatosDocumentoUpdate.as_view(),
            name='editar-datos-documento'),
    re_path(r'^datos_documentos/borrar/(?P<pk>\d+)/$', DatosDocumentoDelete.as_view(),
            name='borrar-datos-documento'),
    re_path(r'^marco-(?P<tipo>metodologico|juridico|teorico)/$', MarcoListView.as_view(),
            name='lista-marcos'),
    re_path(r'^marco-(?P<tipo>metodologico|juridico|teorico)/crear$', MarcoFormView.as_view(),
            name='crear-marco'),
    re_path(r'^marco-(?P<tipo>metodologico|juridico|teorico)/(?P<pk>\d+)/$',
            MarcoDetailView.as_view(), name='detalles-marco'),
    re_path(r'^marco-(?P<tipo>metodologico|juridico|teorico)/eliminar/(?P<pk>\d+)/$',
            delete_marco_view, name='eliminar-marco'),
    re_path(r'^marco-(?P<tipo>metodologico|juridico|teorico)/editar/(?P<pk>\d+)/$',
            MarcoFormView.as_view(), name='editar-marco'),

    path('descripcion_proyecto/', DescripcionProyectoList.as_view(),
         name='lista-detalles-proyecto'),
    path('descripcion_proyecto/nuevo/', DescripcionProyectoCreate.as_view(),
         name='nuevo-detalles-proyecto'),
    re_path(r'^descripcion_proyecto/(?P<pk>\d+)/$', DescripcionProyectoDetail.as_view(),
            name='detalles-proyecto'),
    re_path(r'^descripcion_proyecto/editar/(?P<pk>\d+)/$', DescripcionProyectoUpdate.as_view(),
            name='editar-detalles-proyecto'),
    re_path(r'^descripcion_proyecto/borrar/(?P<pk>\d+)/$', DescripcionProyectoDelete.as_view(),
            name='borrar-detalles-proyecto'),
    path('recomendacion_proyecto/', RecomendacionProyectoListView.as_view(),
         name='lista-recomendaciones-proyecto'),
    path('recomendacion_proyecto/nuevo/', RecomendacionProyectoCreateView.as_view(),
         name='nuevo-recomendaciones-proyecto'),
    re_path(r'^recomendacion_proyecto/(?P<pk>\d+)/$', RecomendacionProyectoDetailView.as_view(),
            name='recomendaciones-proyecto'),
    re_path(r'^recomendacion_proyecto/editar/(?P<pk>\d+)/$',
            RecomendacionProyectoUpdateView.as_view(),
            name='editar-recomendaciones-proyecto'),
    re_path(r'^recomendacion_proyecto/borrar/(?P<pk>\d+)/$',
            RecomendacionProyectoDeleteView.as_view(),
            name='borrar-recomendaciones-proyecto'),
    path('conclusiones_proyecto/', ConclusionesListView.as_view(),
         name='lista-conclusiones'),
    path('conclusiones_proyecto/nuevo/', ConclusionesCreateView.as_view(),
         name='nueva-conclusiones-proyecto'),
    re_path(r'^conclusiones_proyecto/(?P<pk>\d+)/$', ConclusionDetailView.as_view(),
            name='conclusiones-proyecto'),
    re_path(r'^conclusiones_proyecto/editar/(?P<pk>\d+)/$', ConclusionUpdateView.as_view(),
            name='editar-conclusiones-proyecto'),
    re_path(r'^conclusiones_proyecto/borrar/(?P<pk>\d+)/$', ConclusionDeleteView.as_view(),
            name='borrar-conclusiones-proyecto'),
    path('caracteristicas_medio/', MedioList.as_view(),
         name='lista-medios'),
    path('caracteristicas_medio/nuevo/', MedioCreate.as_view(),
         name='nuevo-medio'),
    re_path(r'^caracteristica_medio/(?P<pk>\d+)/$', MedioDetail.as_view(),
            name='detalles-medio'),
    re_path(r'^caracteristica_medio/editar/(?P<pk>\d+)/$', MedioUpdate.as_view(),
            name='editar-detalles-medio'),
    re_path(r'^caracteristica_medio/borrar/(?P<pk>\d+)/$', MedioDelete.as_view(),
            name='borrar-detalles-medio'),
    path('caracteristica_medio/<int:pk>/nueva_caracteristica/',
         CaracteristicaMedioCreate.as_view(), name='nueva-caracteristica'),
    path(
        'caracteristica_medio/editar/caracteristica/<int:pk>/',
        CaracteristicaMedioUpdate.as_view(),
        name='editar-detalles-caracteristica'),
    path(
        'caracteristica_medio/borrar/caracteristica/<int:pk>/',
        CaracteristicaMedioDelete.as_view(),
        name='borrar-detalles-caracteristica'),
    path('caracteristica_medio/detalles/caracteristica/<int:pk>/',
         CaracteristicaMedioDetail.as_view(), name='detalles-caracteristica'),
    path('caracteristica_medio/<int:pk>/nueva_subcaracteristica/',
         SubaracteristicaMedioCreate.as_view(), name='nueva-subcaracteristica'),
    path(
        'caracteristica_medio/editar/subcaracteristica/<int:pk>/',
        SubaracteristicaMedioUpdate.as_view(),
        name='editar-detalles-subcaracteristica'),
    path(
        'caracteristica_medio/borrar/subcaracteristica/<int:pk>/',
        SubaracteristicaMedioDelete.as_view(),
        name='borrar-detalles-subcaracteristica'),
    path('costos/', CostoHumanoList.as_view(),
         name='costos'),
    path('costos/nuevo-costo-humano/', CostoHumanoCreate.as_view(),
         name='nuevo-costo'),
    path('costos/nuevo-costo-servicio/', CostoHumanoServiciosCreate.as_view(),
         name='nuevo-costo-servicios'),
    path('costos/nuevo-costo-pasaje/', CostoHumanoPasajeCreate.as_view(),
         name='nuevo-costo-pasaje'),
    path('costos/nuevo-costo-recursos/', CostoMaterialRecursosCreate.as_view(),
         name='nuevo-costo-recursos'),
    path('costos/nuevo-costo-oficina/', CostoMaterialOficinaCreate.as_view(),
         name='nuevo-costo-oficina'),
    path('costos/nuevo-costo-insumos/', CostoMaterialInsumosCreate.as_view(),
         name='nuevo-costo-insumos'),
    path('costoshumano/editar/<int:pk>/', CostoHumanoUpdate.as_view(),
         name='editar-costohumano'),
    path('costoshumano/eliminar/<int:pk>/', CostoHumanoDelete.as_view(),
         name='borrar-costohumano'),
    path('costosmaterial/editar/<int:pk>/', CostoMaterialesUpdate.as_view(),
         name='editar-costomaterial'),
    path('costosmaterial/eliminar/<int:pk>/', CostoMaterialesDelete.as_view(),
         name='borrar-costomaterial'),
    path('costos/<slug:success>/', CostoHumanoList.as_view(),
         name='costos-success'),
]

eia_app/forms.py
'''Forms para el uso del crud del consultor'''

from django import forms
from .models import (
    Organizacion, Responsable, Solicitante,
    DatosProyecto, DatosDocumento, DescripcionProyecto,
    RecomendacionProyecto, ConclusionProyecto,
    Medio, CaracteristicaMedio, SubaracteristicaMedio
)


class OrganizacionCreateForm(forms.ModelForm):
    '''Form del modelo organizacion'''
    class Meta:  # pylint: disable=too-few-public-methods
        '''Clase meta del formulario'''
        model = Organizacion
        fields = '__all__'
        exclude = ['proyecto'] # pylint: disable=modelform-uses-exclude


class SolicitanteCreateForm(forms.ModelForm):
    '''Form del modelo solicitante'''
    class Meta:  # pylint: disable=too-few-public-methods
        '''Clase meta del formulario'''
        model = Solicitante
        fields = '__all__'
        exclude = ['proyecto'] # pylint: disable=modelform-uses-exclude

class ResponsableCreateForm(forms.ModelForm):
    '''Form del modelo solicitante'''
    class Meta:  # pylint: disable=too-few-public-methods
        '''Clase meta del formulario'''
        model = Responsable
        fields = '__all__'
        exclude = ['proyecto'] # pylint: disable=modelform-uses-exclude

class DatosProyectoCreateForm(forms.ModelForm):
    '''Form del modelo datos proyecto'''
    class Meta:  # pylint: disable=too-few-public-methods
        '''Clase meta del formulario'''
        model = DatosProyecto
        fields = ('titulo', 'ubicacion', 'area', 'tipo')
        exclude = ['proyecto'] # pylint: disable=modelform-uses-exclude


class DatosDocumentoCreateForm(forms.ModelForm):
    '''Form del modelo datos de documentos'''
    class Meta:  # pylint: disable=too-few-public-methods
        '''Clase meta del formulario'''
        model = DatosDocumento
        fields = '__all__'
        exclude = ['proyecto'] # pylint: disable=modelform-uses-exclude

class MarcoForm(forms.Form):
    """Form para el marco (metodologico, juridico o teorico) de un proyecto."""
    contenido = forms.CharField(widget=forms.Textarea, label='Contenido')

class DescripcionProyectoCreateForm(forms.ModelForm):
    '''Form del modelo descripcion de proyectos'''
    class Meta:  # pylint: disable=too-few-public-methods
        '''Clase meta del formulario'''
        model = DescripcionProyecto
        fields = '__all__'
        exclude = ['proyecto'] # pylint: disable=modelform-uses-exclude

class RecomendacionProyectoCreateForm(forms.ModelForm):
    '''Form del modelo recomendaciones de proyectos'''
    class Meta:  # pylint: disable=too-few-public-methods
        '''Clase meta del formulario'''
        model = RecomendacionProyecto
        fields = '__all__'
        exclude = ['proyecto'] # pylint: disable=modelform-uses-exclude

class ConclusionProyectoCreateForm(forms.ModelForm):
    '''Form del modelo conclusiones de proyectos'''
    class Meta: # pylint: disable=too-few-public-methods
        '''Clase meta del formulario'''
        model = ConclusionProyecto
        fields = ['conclusiones']

class MedioCreateForm(forms.ModelForm):
    '''Form del modelo medio'''
    class Meta:  # pylint: disable=too-few-public-methods
        '''Clase meta del formulario'''
        model = Medio
        fields = '__all__'
        exclude = ['proyecto'] # pylint: disable=modelform-uses-exclude

class CaracteristicaMedioCreateForm(forms.ModelForm):
    '''Form del modelo medio'''
    class Meta:  # pylint: disable=too-few-public-methods
        '''Clase meta del formulario'''
        model = CaracteristicaMedio
        fields = '__all__'

class SubaracteristicaMedioCreateForm(forms.ModelForm):
    '''Form del modelo medio'''
    class Meta:  # pylint: disable=too-few-public-methods
        '''Clase meta del formulario'''
        model = SubaracteristicaMedio
        fields = '__all__'

eia_app/templates/eia_app/responsables/delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<form method="post">
  {% csrf_token %}
  <p>¿Estás seguro que deseas borrar el responsable "{{ object.nombre }}"?</p>
  <button type="submit" class="btn btn-primary">Aceptar</button>
</form>

{% endblock %}

eia_app/templates/eia_app/responsables/detail.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'configuracion/css/configuracion_main.css' %}">
<link rel="stylesheet" href="{% static 'css/details.css' %}">
{% endblock %}
{% block content %}
<div class="row p-3 justify-content-center mb-3 titulo all-rounded">
		<div class="col-md-9 col-sm-11 text-center">
        <h3> Detallles del responsable: {{responsable.nombre}} {{responsable.apellido}} </h3>
		</div>
</div>
<div class="grid-container" style="margin-left:10%">


                <div class="grid-item">
                        <div class="text-col">
                            <p class="title">Nombre y Apellido </p>
                            <p>{{ responsable.nombre}} {{responsable.apellido}} </p>
                        </div>
                </div>
                

                <div class="grid-item">
                        <div class="text-col">
                            <p class="title">Cédula</p>
                            <p>{{ responsable.cedula }}</p>
                        </div>
                </div>

                {% if responsable.pasaporte %}
                <div class="grid-item">
                        <div class="text-col">
                            <p class="title">Pasaporte</p>
                            <p>{{ responsable.pasaporte }}</p>
                        </div>
                </div>
                {% endif %}


                

                <div class="grid-item">
                        <div class="text-col">
                            <p class="title">Proyecto</p>
                            <p><a href="{% url "consultor-crud:detalles-datos-proyecto"  responsable.proyecto.id %}">{{ responsable.proyecto }}</a></p>
                        </div>
                </div>
        
                <div class="grid-item">
                        <div class="text-col">
                            <p class="title">Nivel Académico</p>
                            <p>{{ responsable.nivel_academico }}</p>
                        </div>
                </div>

                <div class="grid-item">
                        <div class="text-col">
                            <p class="title">Tipo responsable</p>
                            <p>{{ responsable.tipo_responsable }}</p>
                        </div>
                </div>




            </div>
      </div>
      </div>


{% endblock %}

eia_app/templates/eia_app/responsables/list.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'configuracion/css/configuracion_main.css' %}">
<link rel="stylesheet" href="{% static 'css/jquery.dataTables.css' %}">
{% endblock %}

{% block content %}
<div class="row p-3 justify-content-center mb-3 titulo all-rounded">
		<div class="col-md-9 col-sm-11 text-center">
        <h3>Lista de responsables</h3>
		</div>
</div><p>
    <div class="col-md-1">
        <a id ="add" class="btn rounded btn-crud" href="{% url 'consultor-crud:nuevo-responsable' %}"><i class="material-icons">add</i></a>
  </div>
</p>
<div class="container" style="width:90% !important">
  {%if object_list.count > 0%}
  <table id="responsable" class="display">
      <thead>
          <tr>
              <th>Nombre</th>
              <th>Cédula</th>
              <th>Proyecto</th>
              <th>Tipo de responsable</th>
              <th style="text-align:center;">Ver detalles</th>
              <th style="text-align:center;">Editar</th>
              <th style="text-align:center;">Borrar</th>
          </tr>
      </thead>
      <tbody>
        {% for responsable in object_list %}
          <tr>
              <td>{{ responsable.nombre }}</td>
              <td>{{ responsable.cedula }}</td>
              <td><a href="{% url "consultor-crud:detalles-datos-proyecto"  responsable.proyecto.id %}">{{ responsable.proyecto }}</a></td>
              <td>{{ responsable.get_tipo_responsable_display }}</td>
              <td style="text-align:center;"><a id="detalles{{responsable.id}}" href="{% url "consultor-crud:detalles-responsable"  responsable.id %}"><i class="material-icons" style="color: #77933c">info</i></a></td>
              <td style="text-align:center;"><a id="editar{{responsable.id}}" href="{% url "consultor-crud:editar-responsable" responsable.id %}"><i class="material-icons" style="color: #77933c">edit</i></a></td>
              <td style="text-align:center;"><a id="borrar{{responsable.id}}" href="{% url "consultor-crud:borrar-responsable" responsable.id %}"><i class="material-icons" style="color: #77933c">delete</i></a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <p>No existen datos de responsables agregados a la base de datos</p>
  {% endif %}
</div>

{% endblock %}

<!--BLOQUE DE JS-->

{% block js %}
<script src="{% static 'js/jquery.dataTables.js' %}"></script>
<script>
  $(document).ready( function () {
    $('#responsable').DataTable({
      "language": {
        "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json"
      }
    });
  });
</script>
{% endblock %}