eia/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('consultor-crud/', include('eia_app.urls', namespace='consultor-crud')),
    path('users/', include("users.urls")),
    path('', include('dashboard.urls')),
    path('configuracion/', include("configuracion.urls")),
    path('medidas/', include("medidas.urls")),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, },
            name='media'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

medidas/urls.py
'''Modulo de urls de las medidas '''

from django.urls import path, re_path
from .views import (
    MedidaListView, MedidaDetailView, MedidaDeleteView, medida_form_view
)

app_name = 'medidas' #pylint: disable=invalid-name

urlpatterns = [ #pylint: disable=invalid-name
    path('', MedidaListView.as_view(),
         name='lista-medidas'),
    path('nuevo/', medida_form_view,
         name='nueva-medida'),
    re_path(r'^editar/(?P<pk>\d+)/$', medida_form_view,
            name='editar-medida'),
    re_path(r'^(?P<pk>\d+)/$', MedidaDetailView.as_view(),
            name='detalles-medida'),
    re_path(r'^borrar/(?P<pk>\d+)/$', MedidaDeleteView.as_view(),
            name='borrar-medida'),
]

medidas/models.py
"""
Modelos para el modulo de medidas
"""
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _  # pylint: disable=unused-import

# Create your models here.
class Medida(models.Model):
    """
    Declaracion de modelo de Medidas de eia.
    """
    nomenclatura = models.CharField(max_length=10, unique=True, verbose_name='Nomenclatura')
    nombre = models.CharField(max_length=100, verbose_name='Nombre')
    TIPO_CORRECTIVA = 0
    TIPO_CHOICES = (
        (TIPO_CORRECTIVA, 'Correctiva'),
    )
    tipo = models.IntegerField(choices=TIPO_CHOICES, verbose_name='Tipo')
    MEDIO_FISICO = 0
    MEDIO_BIOLOGICO = 1
    MEDIO_SOCIO_CULTURAL = 2
    MEDIO_CHOICES = (
        (MEDIO_FISICO, 'Físico'),
        (MEDIO_BIOLOGICO, 'Biológico'),
        (MEDIO_SOCIO_CULTURAL, 'Socio-Cultural')
    )
    medio = models.IntegerField(choices=MEDIO_CHOICES, verbose_name='Medio')
    descripcion = models.TextField(verbose_name='Descripción')
    marco_juridico = models.TextField(verbose_name='Marco Jurídico')
    area = models.TextField(verbose_name='Área')
    responsable = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,
                                    verbose_name='Responsable', null=True)

class Impacto(models.Model):
    """ Tabla de Impactos que sirve de atributo multivalor para las medidas """
    medida = models.ForeignKey(Medida, related_name='impactos', on_delete=models.CASCADE)
    descripcion = models.CharField(max_length=200, verbose_name='Descripción')

class Objetivo(models.Model):
    """ Tabla de Objetivos que sirve de atributo multivalor para las medidas """
    medida = models.ForeignKey(
        Medida, related_name='objetivos', on_delete=models.CASCADE)
    descripcion = models.CharField(max_length=200, verbose_name='Descripción')

class IndicadorDeCumplimiento(models.Model):
    """
    Tabla de Indicador De Cumplimientos que sirve de atributo multivalor para las medidas
    """
    medida = models.ForeignKey(
        Medida, related_name='indicadoresdecumplimientos', on_delete=models.CASCADE)
    descripcion = models.CharField(max_length=200, verbose_name='Descripción')

medidas/forms.py
'''Forms para el uso de lista de medidas'''

from django import forms
from django.forms import inlineformset_factory
from .models import (
    Medida, Impacto, IndicadorDeCumplimiento, Objetivo
)


class MedidaForm(forms.ModelForm):
    '''Form del modelo medida'''
    class Meta:  # pylint: disable=too-few-public-methods
        '''Clase meta del formulario'''
        model = Medida
        fields = '__all__'

# pylint: disable=invalid-name
ImpactoFormSet = inlineformset_factory(
    Medida, Impacto, can_delete=True, fields=('descripcion',), extra=0, min_num=1)
ObjetivoFormSet = inlineformset_factory(
    Medida, Objetivo, can_delete=True, fields=('descripcion',), extra=0, min_num=1)
IndicadorDeCumplimientoFormSet = inlineformset_factory(
    Medida, IndicadorDeCumplimiento, can_delete=True, fields=('descripcion',),
    extra=0, min_num=1)

medidas/views.py
'''Views del crud del consultor'''

from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.db import transaction
from django.views.generic import (DetailView,
                                  ListView,
                                  DeleteView)
from django.urls import reverse_lazy
from .models import (
    Medida
)
from .forms import (
    MedidaForm, ImpactoFormSet, ObjetivoFormSet, IndicadorDeCumplimientoFormSet
)

class MedidaListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):  # pylint: disable=too-many-ancestors
    '''Listar las medidas'''
    model = Medida
    template_name = 'medidas/list.html'
    permission_required = ('medidas.view_medida',
                           'medidas.view_impacto', 'medidas.view_objetivo',
                           'medidas.view_indicadordecumplimiento')

class MedidaDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):  # pylint: disable=too-many-ancestors
    '''Detalles de una medida'''
    model = Medida
    template_name = 'medidas/detail.html'
    permission_required = ('medidas.view_medida',
                           'medidas.view_impacto', 'medidas.view_objetivo',
                           'medidas.view_indicadordecumplimiento')


class MedidaDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):  # pylint: disable=too-many-ancestors
    '''Eliminar una medida'''
    model = Medida
    template_name = 'medidas/delete.html'
    success_url = reverse_lazy('medidas:lista-medidas')
    permission_required = ('medidas.delete_medida',
                           'medidas.delete_impacto', 'medidas.delete_objetivo',
                           'medidas.delete_indicadordecumplimiento')

@login_required
@permission_required(('medidas.view_medida', 'medidas.view_impacto', 'medidas.view_objetivo',
                      'medidas.view_indicadordecumplimiento'), raise_exception=True)
@transaction.atomic
def medida_form_view(request, pk=None): # pylint: disable=invalid-name
    """
    Vista que maneja la creacion de medidas tomando en cuenta
    las relaciones de sus tablas multivalores. El uso de transaction.atomic
    es para evitar crear un objeto sin crear los dependientes.
    """
    try:
        medida = Medida.objects.get(pk=pk)
    except Medida.DoesNotExist:
        medida = Medida()

    medida_form = MedidaForm(instance=medida)
    impacto_formset = ImpactoFormSet(instance=medida)
    objetivo_formset = ObjetivoFormSet(instance=medida)
    indicador_formset = IndicadorDeCumplimientoFormSet(instance=medida)
    if request.method == 'POST':
        medida_form = MedidaForm(request.POST, instance=medida)
        impacto_formset = ImpactoFormSet(request.POST, instance=medida)
        objetivo_formset = ObjetivoFormSet(request.POST, instance=medida)
        indicador_formset = IndicadorDeCumplimientoFormSet(
            request.POST, instance=medida)
        if medida_form.is_valid():
            medida_form.save()

            if impacto_formset.is_valid() and objetivo_formset.is_valid() and\
                indicador_formset.is_valid():
                impacto_formset.save()
                objetivo_formset.save()
                indicador_formset.save()
                return redirect('medidas:lista-medidas')
    return render(request, 'medidas/form.html', {
        'medida_form': medida_form,
        'impacto_formset': impacto_formset,
        'objetivo_formset': objetivo_formset,
        'indicador_formset': indicador_formset,
    })

templates/medidas/delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<form method="post">
  {% csrf_token %}
  <p>¿Estás seguro que deseas borrar la medida "{{ object.nombre }}"?</p>
  <button id='id_aceptar' type="submit" class="btn btn-primary">Aceptar</button>
</form>
{% endblock %}

templates/medidas/detail.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/details.css' %}">
{% endblock %}
{% block content %}

<h3> Detalles de la medida: {{medida.nombre}}</h3>
<br>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h3 class="title">Nombre: </h3>
      <p>{{ medida.nombre}} </p>
      
      <h3 class="title">Tipo: </h3>
      <p>{{ medida.get_tipo_display}} </p>
      
      <h3 class="title">Medio: </h3>
      <p>{{ medida.get_medio_display}} </p>

      <h3 class="title">Descripción: </h3>
      <p>{{ medida.descripcion}} </p>

      <h3 class="title">Marco jurídico: </h3>
      <p>{{ medida.marco_juridico}} </p>

      <h3 class="title">Área: </h3>
      <p>{{ medida.area}} </p>
    </div>
    <div class="col-md-6">
      <h3 class="title">Nombre del responsable: </h3>
      <p>{{ medida.nombre_responsable}} </p>

      <h3 class="title">Apellido del responsable: </h3>
      <p>{{ medida.apellido_responsable}} </p>


      <h3 class="title">CI del responsable: </h3>
      <p>{{ medida.ci_responsable}} </p>

      <h3 class="title">Nivel académico del responsable: </h3>
      <p>{{ medida.nivel_academico_responsable}} </p>

      <h3 class="title">Impactos afectados: </h3>
      <ul>
        {% for impacto in medida.impactos.all %}
          <li>
            <p>{{impacto.descripcion}}</p>
          </li>
        {% endfor %}
      </ul>

      <h3 class="title">Objetivo de la medida: </h3>
      <ul>
        {% for objetivo in medida.objetivos.all %}
          <li>
            <p>{{objetivo.descripcion}}</p>
          </li>
        {% endfor %}
      </ul>

      <h3 class="title">Indicadores de cumplimiento: </h3>
      <ul>
        {% for indicador in medida.indicadoresdecumplimientos.all %}
          <li>
            <p>{{indicador.descripcion}}</p>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>

</div>

{% endblock %}

templates/medidas/form.html
{% extends 'base.html' %}
{% load static %}
{% load materializecss %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}


{% block css %}
<style>
  .formset-row {
    align-items: center;
  }
  .formset-row .btn-sm {
    margin-bottom: 1rem;
  }
</style>
{% endblock css %}
  
{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8">
      <h3 class="mt-2">Agregar {{ nombre }}</h3>
      <hr class="mt-0 mb-4">
      <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <!-- Formulario sin impacto, indicadores y objetivos -->
          {{ medida_form | crispy }}
          <!-- Formulario de impactos -->
          <div id="{{impacto_formset.prefix}}" class="row">
            <div class="col">
              <h3>Impactos</h3>
            </div>
            {% for error in impacto_formset.non_field_errors %}
            {{error}}
            {% endfor %}
            <div class="w-100"></div>
            {{ impacto_formset.management_form }}
            <div class="col">
              {% for form in impacto_formset %}
              <div class="row formset-row">
                <div class="col">
                  {{form.id}}
                  {{form.medida}}
                  <div class="form-group">
                    {{form.descripcion.errors}}
                    {% if form.instance.pk %}{{ form.DELETE }}{% endif %}
                    {% render_field form.descripcion class="form-control" placeholder=form.descripcion.label required="required" %}
                  </div>
                  <div class="w-100"></div>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
          <br>

          <!-- Formulario de objetivos -->
          <div id="{{objetivo_formset.prefix}}" class="row">
            <div class="col">
              <h3>Objetivos</h3>
            </div>
            {% for error in objetivo_formset.non_field_errors %}
            {{error}}
            {% endfor %}
            <div class="w-100"></div>
            {{ objetivo_formset.management_form }}
            <div class="col">
              {% for form in objetivo_formset %}
              <div class="row formset-row">
                <div class="col">
                  {{form.id}}
                  {{form.medida}}
                  <div class="form-group">
                    {% if form.instance.pk %}{{ form.DELETE }}{% endif %}
                    {{form.descripcion.errors}}
                    {% render_field form.descripcion class="form-control" placeholder=form.descripcion.label required="required" %}
                  </div>
                  <div class="w-100"></div>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
          <br>

          <!-- Formulario de indicadores -->
          <div id="{{indicador_formset.prefix}}" class="row">
            <div class="col">
              <h3>Indicadores</h3>
            </div>
            {% for error in indicador_formset.non_field_errors %}
            {{error}}
            {% endfor %}
            <div class="w-100"></div>
            {{ indicador_formset.management_form }}
            <div class="col">
              {% for form in indicador_formset %}
              <div class="row formset-row">
                <div class="col">
                  {{form.id}}
                  {{form.medida}}
                  <div class="form-group">
                    {{form.descripcion.errors}}
                    {% if form.instance.pk %}{{ form.DELETE }}{% endif %}
                    {% render_field form.descripcion class="form-control" placeholder=form.descripcion.label required="required" %}
                  </div>
                  <div class="w-100"></div>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
          <br>

          <button id="agregar" type="submit" class="btn btn-primary">Guardar</button>
        </form>
    </div>
  </div>
</div>
{% endblock %}


{% block js %}
<script src="{% static 'js/jquery.formset.js' %}"></script>
<script>
  $(function() {
    $('#{{indicador_formset.prefix}} .formset-row').formset({
      prefix: '{{indicador_formset.prefix}}',
      formCssClass: '{{indicador_formset.prefix}}-formset',
      addText: 'Añadir indicador',
      deleteText: 'Eliminar indicador',
      addCssClass: 'btn btn-primary btn-sm',
      deleteCssClass: 'btn btn-danger btn-sm'
    })
    $('#{{objetivo_formset.prefix}} .formset-row').formset({
      prefix: '{{objetivo_formset.prefix}}',
      formCssClass: '{{objetivo_formset.prefix}}-formset',
      addText: 'Añadir objetivo',
      deleteText: 'Eliminar objetivo',
      addCssClass: 'btn btn-primary btn-sm',
      deleteCssClass: 'btn btn-danger btn-sm'
    })
    $('#{{impacto_formset.prefix}} .formset-row').formset({
      prefix: '{{impacto_formset.prefix}}',
      formCssClass: '{{impacto_formset.prefix}}-formset',
      addText: 'Añadir impacto',
      deleteText: 'Eliminar impacto',
      addCssClass: 'btn btn-primary btn-sm',
      deleteCssClass: 'btn btn-danger btn-sm'
    })

  })
</script>
{% endblock js %}
  

templates/medidas/list.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/jquery.dataTables.css' %}">
{% endblock %}

{% block content %}

<h3>Lista de medidas</h3>
<p>
  <button type="button" class="btn btn-info"> <a href="{% url "medidas:nueva-medida" %}">Agregar medida</a></button>
</p>
<div class="container" style="width:90% !important">
    {%if object_list.count > 0%}
      <table id="tablamedidas" class="display">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Tipo</th>
                <th>Medio</th>
                <th style="text-align:center;">Ver detalles</th>
                <th style="text-align:center;">Editar</th>
                <th style="text-align:center;">Borrar</th>
            </tr>
        </thead>
        <tbody>
          {% for medida in object_list %}
            <tr>
                <td>{{ medida.nombre }}</td>
                <td>{{ medida.get_tipo_display }}</td>
                <td>{{ medida.get_medio_display }}</td>
                <td style="text-align:center;"><a href="{% url "medidas:detalles-medida"  medida.id %}"><i class="material-icons" style="color: #77933c">info</i></a></td>
                <td style="text-align:center;"><a href="{% url "medidas:editar-medida" medida.id %}"><i class="material-icons" style="color: #77933c">edit</i></a></td>
                <td style="text-align:center;"><a href="{% url "medidas:borrar-medida" medida.id %}"><i class="material-icons" style="color: #77933c">delete</i></a></td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      {% else %}
      <p>No existen medidas agregadas a la base de datos</p>
    {% endif %}
</div>

{% endblock %}

<!--BLOQUE DE JS-->

{% block js %}
<script src="{% static 'js/jquery.dataTables.js' %}"></script>
<script>
  $(document).ready( function () {
    $('#tablamedidas').DataTable({
      "language": {
        "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json"
      }
    });
  });
</script>
{% endblock %}